In [132]:
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder, MinMaxScaler

numeric = ['age', 'LQ1_mn']
categorical = ['sex', 'EC1_1', 'marri_1', 'BP1', 'BP5', 'BS3_1', 'LQ4_00', 'LQ1_sb', 'BP6_31']
one_hot = ['edu', 'D_1_1', 'BD1_11', 'BD2_31']

warnings.filterwarnings('ignore')

In [133]:
df = pd.read_csv('./temptemp.csv')
df['BE3_31'].replace(9, np.nan, inplace=True)
df = df[pd.notna(df['BE3_31'])]

In [152]:
df['BD2_31'].unique()

array([3., 4., 0., 5., 2., 1.])

In [134]:
for col in df.columns:
    if col != 'BE3_31':
        df[col] = df[col].fillna(df[col].mode()[0])

In [144]:
encoder = OneHotEncoder(sparse=False)
encoder.fit(df[one_hot])

ohe = encoder.transform(df[one_hot])

In [148]:
pd.get_dummies(df[one_hot], dtype=int)

BD1_11  BD2_31  edu_고졸  edu_대졸이상  edu_중졸  edu_초졸이하  D_1_1_나쁨  D_1_1_보통  \
0        4.0     3.0       0         0       0         1         1         0   
1        6.0     4.0       1         0       0         0         0         1   
2        5.0     4.0       0         1       0         0         0         1   
3        1.0     0.0       1         0       0         0         0         1   
4        1.0     0.0       0         0       0         1         0         0   
...      ...     ...     ...       ...     ...       ...       ...       ...   
5234     1.0     0.0       1         0       0         0         0         1   
5235     3.0     3.0       0         1       0         0         0         0   
5236     4.0     1.0       1         0       0         0         0         1   
5237     1.0     0.0       0         0       0         1         1         0   
5238     0.0     0.0       0         1       0         0         0         0   

      D_1_1_좋음  
0            0  
1            0  
2            0  
3            0  
4            1  
...        ...  
5234         0  
5235         1  
5236         0  
5237         0  
5238         1  

[5054 rows x 9 columns]

In [141]:
pd.concat([df.drop(one_hot, axis=1), pd.DataFrame(ohe)], axis=1).isna().sum()

age        170
sex        170
EC1_1      170
marri_1    170
BP1        170
BP5        170
LQ_1EQL    170
LQ_2EQL    170
LQ_3EQL    170
LQ_4EQL    170
LQ_5EQL    170
BS3_1      170
LQ4_00     170
LQ1_sb     170
LQ1_mn     170
BP6_10     170
BP6_31     170
BE3_31     170
BE5_1      170
0          170
1          170
2          170
3          170
4          170
5          170
6          170
7          170
8          170
9          170
10         170
11         170
12         170
13         170
14         170
15         170
16         170
17         170
18         170
19         170
dtype: int64

In [130]:
df.isna().sum()

age        170
sex        170
edu        170
EC1_1      170
marri_1    170
BP1        170
BP5        170
D_1_1      170
LQ_1EQL    170
LQ_2EQL    170
LQ_3EQL    170
LQ_4EQL    170
LQ_5EQL    170
BS3_1      170
LQ4_00     170
LQ1_sb     170
LQ1_mn     170
BD1_11     170
BD2_31     170
BP6_10     170
BP6_31     170
BE3_31     170
BE5_1      170
0          170
1          170
2          170
3          170
4          170
5          170
6          170
7          170
8          170
9          170
10         170
11         170
12         170
13         170
14         170
15         170
16         170
17         170
18         170
19         170
dtype: int64

In [86]:
encoder = MinMaxScaler()
encoder.fit(df[numeric])

num = encoder.transform(df[numeric])
df = pd.concat([df.drop(numeric, axis=1), pd.DataFrame(num, columns=encoder.feature_names_in_)], axis=0)

In [87]:
df['BE3_31'].unique()

array([ 6.,  8.,  1.,  3.,  5.,  4.,  2.,  7., nan])

In [77]:
df['BE3_31'].value_counts()

BE3_31
8.0    1726
1.0    1058
4.0     586
6.0     433
3.0     419
5.0     331
2.0     280
7.0     221
Name: count, dtype: int64

In [61]:
df['BE3_31'] = df.pop('BE3_31')

In [66]:
from catboost import CatBoostClassifier

ml = CatBoostClassifier(random_state=42)

In [67]:
X = df.drop('BE3_31', axis=1)
y = df['BE3_31']

In [70]:
df['BE3_31'].unique()

array([ 6.,  8.,  1.,  3.,  5.,  4.,  2.,  7., nan])

In [69]:
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X, y, stratify=y, test_size=.2, random_state=42) 

ValueError: Input y contains NaN.